package vista;

/**
 *
 * @author Magh
 */
public class FrmProducto extends javax.swing.JFrame {
    /**
     * Crea nuevo formulario FrmProducto
     */
    public FrmProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneProducto = new javax.swing.JTabbedPane();
        panelAdministrar = new javax.swing.JPanel();
        scrollPaneAdm = new javax.swing.JScrollPane();
        tablaAdmProducto = new javax.swing.JTable();
        modeloTablaAdmProducto = new javax.swing.table.DefaultTableModel(); // TableModel
        etiAdmIdProducto = new javax.swing.JLabel();
        etiAdmCategoria = new javax.swing.JLabel();
        etiAdmTipo = new javax.swing.JLabel();
        etiAdmCodigo = new javax.swing.JLabel();
        etiAdmMarca = new javax.swing.JLabel();
        txtAdmIdProducto = new javax.swing.JTextField();
        txtAdmCodigo = new javax.swing.JTextField();
        txtAdmMarca = new javax.swing.JTextField();
        cmbAdmCategoria = new javax.swing.JComboBox<>();
        cmbAdmTipo = new javax.swing.JComboBox<>();
        chkAdmIdProducto = new javax.swing.JCheckBox();
        chkAdmCategoria = new javax.swing.JCheckBox();
        chkAdmTipo = new javax.swing.JCheckBox();
        chkAdmCodigo = new javax.swing.JCheckBox();
        chkAdmMarca = new javax.swing.JCheckBox();
        btnAdmBuscar = new javax.swing.JButton();
        tglbtnAdmEditar = new javax.swing.JToggleButton();
        btnAdmGuardar = new javax.swing.JButton();
        panelComprar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar Productos");
        setMinimumSize(new java.awt.Dimension(1000, 720));
        setName("frmProducto"); // NOI18N

        tabbedPaneProducto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tabbedPaneProducto.setMinimumSize(new java.awt.Dimension(1000, 720));
        tabbedPaneProducto.setPreferredSize(new java.awt.Dimension(1000, 720));

        panelAdministrar.setPreferredSize(new java.awt.Dimension(1000, 680));

        scrollPaneAdm.setMinimumSize(new java.awt.Dimension(100, 100));
        scrollPaneAdm.setPreferredSize(new java.awt.Dimension(800, 370));

        modeloTablaAdmProducto.setColumnIdentifiers(new String[] {
            // Jalar de la BD todas las cabeceras de la tabla Producto
            "ID Producto", "ID Categoria", "ID_Tipo", "Codigo", "Marca", "Descripcion", "Caracteristicas", "Precio_Unitario", "Stock", "Descontinuado"
        });
        tablaAdmProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaAdmProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaAdmProducto.setModel(modeloTablaAdmProducto);
        tablaAdmProducto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaAdmProducto.setAutoscrolls(false);
        tablaAdmProducto.setCellSelectionEnabled(true);
        tablaAdmProducto.setFillsViewportHeight(true);
        tablaAdmProducto.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tablaAdmProducto.setMinimumSize(new java.awt.Dimension(90, 90));
        tablaAdmProducto.setRowHeight(30);
        tablaAdmProducto.setShowVerticalLines(true);
        tablaAdmProducto.setSurrendersFocusOnKeystroke(true);
        tablaAdmProducto.getTableHeader().setReorderingAllowed(false);
        scrollPaneAdm.setViewportView(tablaAdmProducto);

        etiAdmIdProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiAdmIdProducto.setText("ID Producto:");
        etiAdmIdProducto.setMaximumSize(new java.awt.Dimension(100, 30));
        etiAdmIdProducto.setMinimumSize(new java.awt.Dimension(100, 30));
        etiAdmIdProducto.setPreferredSize(new java.awt.Dimension(100, 30));

        etiAdmCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiAdmCategoria.setText("Categoria:");
        etiAdmCategoria.setMaximumSize(new java.awt.Dimension(80, 30));
        etiAdmCategoria.setMinimumSize(new java.awt.Dimension(80, 30));
        etiAdmCategoria.setName(""); // NOI18N
        etiAdmCategoria.setPreferredSize(new java.awt.Dimension(80, 30));

        etiAdmTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiAdmTipo.setText("Tipo:");
        etiAdmTipo.setPreferredSize(new java.awt.Dimension(39, 30));

        etiAdmCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiAdmCodigo.setText("Código:");
        etiAdmCodigo.setPreferredSize(new java.awt.Dimension(63, 30));

        etiAdmMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiAdmMarca.setText("Marca:");
        etiAdmMarca.setPreferredSize(new java.awt.Dimension(52, 30));

        txtAdmIdProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAdmIdProducto.setMinimumSize(new java.awt.Dimension(200, 30));
        txtAdmIdProducto.setPreferredSize(new java.awt.Dimension(200, 30));

        txtAdmCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAdmCodigo.setMinimumSize(new java.awt.Dimension(200, 30));
        txtAdmCodigo.setPreferredSize(new java.awt.Dimension(200, 30));

        txtAdmMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAdmMarca.setMinimumSize(new java.awt.Dimension(200, 30));
        txtAdmMarca.setPreferredSize(new java.awt.Dimension(200, 30));

        cmbAdmCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbAdmCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAdmCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbAdmCategoria.setMinimumSize(new java.awt.Dimension(94, 30));
        cmbAdmCategoria.setPreferredSize(new java.awt.Dimension(94, 30));

        cmbAdmTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbAdmTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAdmTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbAdmTipo.setMinimumSize(new java.awt.Dimension(94, 30));
        cmbAdmTipo.setPreferredSize(new java.awt.Dimension(94, 30));

        chkAdmIdProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAdmIdProducto.setSelected(true);
        chkAdmIdProducto.setText("Y");
        chkAdmIdProducto.setToolTipText("Si se selecciona, el criterio de búsqueda incluirá el ID Producto.");
        chkAdmIdProducto.setMaximumSize(new java.awt.Dimension(35, 30));
        chkAdmIdProducto.setMinimumSize(new java.awt.Dimension(35, 30));
        chkAdmIdProducto.setPreferredSize(new java.awt.Dimension(35, 30));

        chkAdmCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAdmCategoria.setText("Y");
        chkAdmCategoria.setToolTipText("Si se selecciona, el criterio de búsqueda incluirá la Categoria.");
        chkAdmCategoria.setMaximumSize(new java.awt.Dimension(35, 30));
        chkAdmCategoria.setMinimumSize(new java.awt.Dimension(35, 30));
        chkAdmCategoria.setPreferredSize(new java.awt.Dimension(35, 30));

        chkAdmTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAdmTipo.setText("Y");
        chkAdmTipo.setToolTipText("Si se selecciona, el criterio de búsqueda incluirá el Tipo.");
        chkAdmTipo.setMaximumSize(new java.awt.Dimension(35, 30));
        chkAdmTipo.setMinimumSize(new java.awt.Dimension(35, 30));
        chkAdmTipo.setPreferredSize(new java.awt.Dimension(35, 30));

        chkAdmCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAdmCodigo.setText("Y");
        chkAdmCodigo.setToolTipText("Si se selecciona, el criterio de búsqueda incluirá el Código.");
        chkAdmCodigo.setMaximumSize(new java.awt.Dimension(35, 30));
        chkAdmCodigo.setMinimumSize(new java.awt.Dimension(35, 30));
        chkAdmCodigo.setPreferredSize(new java.awt.Dimension(35, 30));

        chkAdmMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAdmMarca.setText("Y");
        chkAdmMarca.setToolTipText("Si se selecciona, el criterio de búsqueda incluirá la Marca.");
        chkAdmMarca.setMaximumSize(new java.awt.Dimension(35, 30));
        chkAdmMarca.setMinimumSize(new java.awt.Dimension(35, 30));
        chkAdmMarca.setPreferredSize(new java.awt.Dimension(35, 30));

        btnAdmBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdmBuscar.setText("Buscar");
        btnAdmBuscar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnAdmBuscar.setMinimumSize(new java.awt.Dimension(100, 30));
        btnAdmBuscar.setPreferredSize(new java.awt.Dimension(100, 30));

        tglbtnAdmEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tglbtnAdmEditar.setText("Editar");
        tglbtnAdmEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tglbtnAdmEditar.setMaximumSize(new java.awt.Dimension(120, 30));
        tglbtnAdmEditar.setMinimumSize(new java.awt.Dimension(120, 30));
        tglbtnAdmEditar.setPreferredSize(new java.awt.Dimension(120, 30));
        tglbtnAdmEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglbtnAdmEditarActionPerformed(evt);
            }
        });

        btnAdmGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdmGuardar.setText("Guardar");
        btnAdmGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAdmGuardar.setMaximumSize(new java.awt.Dimension(120, 30));
        btnAdmGuardar.setMinimumSize(new java.awt.Dimension(120, 30));
        btnAdmGuardar.setPreferredSize(new java.awt.Dimension(120, 30));
        btnAdmGuardar.setVisible(false);
        btnAdmGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdministrarLayout = new javax.swing.GroupLayout(panelAdministrar);
        panelAdministrar.setLayout(panelAdministrarLayout);
        panelAdministrarLayout.setHorizontalGroup(
            panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneAdm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAdministrarLayout.createSequentialGroup()
                        .addGroup(panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiAdmIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiAdmCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiAdmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiAdmMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiAdmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdmCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAdmMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAdmIdProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbAdmCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbAdmTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAdmIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkAdmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkAdmMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkAdmCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAdministrarLayout.createSequentialGroup()
                                .addComponent(chkAdmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(btnAdmBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(tglbtnAdmEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addComponent(btnAdmGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAdministrarLayout.setVerticalGroup(
            panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministrarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtAdmIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiAdmIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAdmIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cmbAdmCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiAdmCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAdmCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(etiAdmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAdmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAdmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglbtnAdmEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtAdmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiAdmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAdmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAdministrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtAdmMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiAdmMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAdmMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(scrollPaneAdm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPaneProducto.addTab("Administrar", panelAdministrar);

        javax.swing.GroupLayout panelComprarLayout = new javax.swing.GroupLayout(panelComprar);
        panelComprar.setLayout(panelComprarLayout);
        panelComprarLayout.setHorizontalGroup(
            panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panelComprarLayout.setVerticalGroup(
            panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );

        tabbedPaneProducto.addTab("Comprar", panelComprar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedPaneProducto.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tglbtnAdmEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglbtnAdmEditarActionPerformed
        if (tglbtnAdmEditar.isSelected()) {
            btnAdmGuardar.setVisible(true);
            // Habilitar la edición a todas las columnas de la tabla.
            tglbtnAdmEditar.setText("Editando");
        } else {
            btnAdmGuardar.setVisible(false);
            // Deshabilitar la edición a todas las columnas de la tabla.
            tglbtnAdmEditar.setText("Editar");
        }
    }//GEN-LAST:event_tglbtnAdmEditarActionPerformed

    private void btnAdmGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmGuardarActionPerformed
        tglbtnAdmEditar.doClick();
    }//GEN-LAST:event_btnAdmGuardarActionPerformed

    //

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmBuscar;
    private javax.swing.JButton btnAdmGuardar;
    private javax.swing.JCheckBox chkAdmCategoria;
    private javax.swing.JCheckBox chkAdmCodigo;
    private javax.swing.JCheckBox chkAdmIdProducto;
    private javax.swing.JCheckBox chkAdmMarca;
    private javax.swing.JCheckBox chkAdmTipo;
    private javax.swing.JComboBox<String> cmbAdmCategoria;
    private javax.swing.JComboBox<String> cmbAdmTipo;
    private javax.swing.JLabel etiAdmCategoria;
    private javax.swing.JLabel etiAdmCodigo;
    private javax.swing.JLabel etiAdmIdProducto;
    private javax.swing.JLabel etiAdmMarca;
    private javax.swing.JLabel etiAdmTipo;
    private javax.swing.JPanel panelAdministrar;
    private javax.swing.JPanel panelComprar;
    private javax.swing.JScrollPane scrollPaneAdm;
    private javax.swing.JTabbedPane tabbedPaneProducto;
    private javax.swing.JTable tablaAdmProducto;
    private javax.swing.table.DefaultTableModel modeloTablaAdmProducto; // TableModel
    private javax.swing.JToggleButton tglbtnAdmEditar;
    private javax.swing.JTextField txtAdmCodigo;
    private javax.swing.JTextField txtAdmIdProducto;
    private javax.swing.JTextField txtAdmMarca;
    // End of variables declaration//GEN-END:variables
}
